title: lichd's Homepage
page-top-title: lichd(lichundong)
top-section-bg-text: 信息资源管理
home-subtitle: lichd(lichundong)&ensp;|&ensp;李春东
copyright-text: '&copy; lichd(lichundong) 2025-2099. All Rights Reserved.'
